version: '3'
services:
  # db:
  #   image: postgres
  #   volumes:
  #     - ./tmp/db:/var/lib/postgresql/data
  # nginx:
  #   build: ./docker_containers/nginx_server
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - puma
    

  puma:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    # depends_on: 
    #   - db
 